import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

// import Image from 'next/image'
import { Hero } from '../styles/Home/hero'

const Home: React.FC = () => {
    return (
        <>
            <Head>
                <title>BEATful - join the music revolution</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <Hero>
                <main>
                    <h1>BEATful</h1>
                    <p>come join us in the music revolution.</p>
                    <div className="btns-hero">
                        <Link href="/about">
                            <button>GET STARTED</button>
                        </Link>
                        <Link href="/about">
                            <button>WATCH TRAILER</button>
                        </Link>
                    </div>
                </main>
            </Hero>
        </>
    )
}

export default Home
